### ISSUE TITLE
New NuGet without log4net

### ISSUE THREAD

**Issue by shaggygi** [Dirkster99/fsc#19]
Noticed one of the latest updates removed log4net.  Don't see an updated NuGet (but could be overlooking).

Could you push a new NuGet package that doesn't have the log4net dependency?

Thanks for your work.  Controls appear to be what I need for a utility I'm working on.

**Comment by Dirkster99** [comment]
Yes, you are right I somehow messed up the versioning and forgot to push the latest version to nuget.
So, I released the current version without any changed to version 3.2.0 and also pushed this out to nuget 
to clean up this situation for the future.

Thanx for the hint, Dirxter

**Comment by Dirkster99** [comment]
Yes, you are right I somehow messed up the versioning and forgot to push the latest version to nuget.
So, I released the current version without any changed to version 3.2.0 and also pushed this out to nuget 
to clean up this situation for the future.

Thanx for the hint, Dirxter

**Comment by shaggygi** [comment]
Thanks for the update 👍
