### ISSUE TITLE
.NET 5 support?

### ISSUE THREAD

**Issue by mathew-odwyer** [Dirkster99/fsc#20]
Any chance for .NET 5 support?

**Comment by Dirkster99** [comment]
I don't mind supporting .NET 5 - could you go ahead an prepare a multi-targeting PR that targets:
-  .NET 5 and
- .NET 4.5.2 ?

Look into [this project](https://github.com/Dirkster99/AvalonDock) if you need guidance.

**Comment by mathew-odwyer** [comment]
I'll hopefully get this done over the next day or two. With work and other life stuff it can get a bit difficult as your probably aware. Thanks for getting back to me so promptly!

**Comment by mathew-odwyer** [comment]
<3 sorry I didn't get back to this like I said I would. Thank you for your efforts.
